### PR TITLE
Feature/typescript integration

### PR DESCRIPTION
**Pull request by NemeSnz**
### What does this PR do?
- Migrate javascript code to typescript
- Add `prepare` npm script to compile to javascript
- Change module entry point to `dist/uplink.js`

#### Related Issues
#18

### CODE REVIEW

**Comment by kmozurkewich** [comment]
@NemeSnz  - thank you for this submission.  We will review over the next few days and provide any feedback.

**Comment by ayush-srivastava-03** [comment]
Hello @NemeSnz  we are currently reviewing PR submitted by you. We will update you shortly.

**Comment by NemeSnz** [comment]
Hi @ayush-srivastava-03, feel free to reach me if you need to discuss anything related to this PR

**Comment by ayush-srivastava-03** [comment]
Hi @NemeSnz , please check and merge the pull request created .

**Pull request merged**
