### PR TITLE
remove unused docsify

### PR DESCRIPTION
**Pull request by thepiwo**

### CODE REVIEW

**Comment by thepiwo** [comment]
@kmozurkewich do you have any feedback regarding this?

**Comment by kmozurkewich** [comment]
Hi @thepiwo  - docsify is used to generate the docs at https://storj-thirdparty.github.io/uplink-nodejs/#/ - what would be the reason for removing it?

**Comment by thepiwo** [comment]
I didn't find the lines of code where it is used in this repo, if so it maybe included as dev dependency only?

Docsify uses an super outdated marked version (which they didn't update for breaking changes), which includes certain voulnerabilites.

https://github.com/docsifyjs/docsify/pull/1503
https://github.com/docsifyjs/docsify/pull/1724

**Comment by kmozurkewich** [comment]
I'll accept this PR and move the docsify dep to devdeps.

**Pull request merged**
